twitter:
  bearer: AAAAAAAAAAAAAAAAAAAAAHsRXgEAAAAAOPlVwivczqiH6kGFX0GTeg3AGtM%3DKGf1KmDUSmBZreLD6eQ2lWAeiL5lCH4qgN47CsglmUmrA28MM9

kafka:
  host: localhost:9092
  topic: tweetsTopic

server:
  port : 8081
